name: My Manual Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name for the workflow"
        default: "dev"
        required: true
        type: string

jobs:
  example:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Display Name
        run: echo "Workflow name is ${{ github.event.inputs.name }}"
      - uses: infovista-opensource/vars-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
