name: My Manual Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name for the workflow"
        default: "dev"
        required: true
        type: string
env:
  environment: dev
jobs:
  example:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Display Name
        run: echo "Workflow name is ${{ github.event.inputs.name }}"
      - uses: infovista-opensource/vars-to-env-action@1.0.0
        with:
          secrets: ${{ toJSON(secrets) }}
          variables: ${{ toJSON(vars) }}
      - name: Extract secrets to HEX
        env:
          secrets: ${{ toJSON(secrets) }}
        run: |
          echo $secrets | jq -r 'keys[] as $k | "echo \"\($k)=\(.[$k] )\" >> $GITHUB_ENV"' > .env.production
          cat .env.production
        shell: bash

      - name: use another   
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          variables: ${{ toJSON(vars) }}

      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Print environment variables
        run: |
          echo "CI_REPOSITORY_OWNER=$CI_REPOSITORY_OWNER"
          echo "CI_REPOSITORY_NAME=$CI_REPOSITORY_NAME"

      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          secrets: ${{ toJSON(secrets) }}
          variables: ${{ toJSON(vars) }}
          TEST:  ${{ secrets.TEST }}

 
