name: Test Buid on Feature Branch
run-name: Build initiated by ${{ github.actor }}
on:
  pull_request:
    branches: [ development ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Setup Java 17 and Maven
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '17'
        cache: 'maven'
        cache-dependency-path: 'pom.xml'
    - name: Update version in pom.xml
      uses: kalyan-mallajosyula/mvn-version-bumper@main
      with:
        trigger_event: 'pull_request'
        increment: 'patch'
    - name: Build with Maven
      env: 
        DEV_ENVIRONMENT_VARIABLE: ${{ vars.DEV_ENVIRONMENT_VARIABLE }}
      run: |
          echo "environment=$DEV_ENVIRONMENT_VARIABLE" > src/main/resources/dev.properties
          mvn clean package
    - name: Sample Deployment
      run: |
          java -Denvironment.file=dev.properties -jar $(ls target/helloenv-*.jar)
          
