name: Create Pull Request to Development
 
on:
  push:
    branches:
      - 'opsrelease/**'
 
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
     - name: chckout code
       uses: actions/checkout@v2

     - name: extract git commit data
       uses: rlespinasse/git-commit-data-action@v1.x

     - name: update author information
       uses: echo ${{env.GIT_COMMIT_AUTHOR_NAME}} >> AUTHOR

     - name: Raise PR
       uses: peter-evans/create-pull-request@v3
       with: 
        branch: "opsdevelopment"
        base: "opsrelease/**"
        title: "auto pr"
        body:
          This is auto pr
        token: ${{ secrets.PAT }}
