name: Create a PR from hotfix to development
run-name: Build initiated by ${{ github.actor }}
on:
  push:
     branches:
       - opshotfix/*
permissions:
  contents: write
jobs:
  create_pr:
     runs-on: ubuntu-latest
     #needs: [codeql_autobuild_check, build_artifact_for_hotfix_to_main]
     #if: github.event.pull.request.base.ref == 'opsdevelopment' && github.event.pull_request.head.ref == 'opsrelease/'
     steps: 
      - name: Checkout code
        uses: actions/checkout@v2
        #with:
        #  ref: ${{ github.ref }}
        #  fetch-depth: '0'
      - name: get commit range
        id: commit_range
        run: echo "::set-output name=range::$(git rev-parse ${{ github.event.before }}..$(git rev-parse ${{ github.sha }})"

      - name: check for new commits
        id: check_commits
        run: |
          commit_range="${{ steps.commit.rage.outputs.range }}"
          if [ -z "$commit_range" ]; then
            echo "No new commits. Exiting"
            exit 0
          fi

      - name: Create Pull request
        if: steps.check_commits.outcome == 'success'
        uses: peter-evans/create-pull-request@v3
        env:  
          GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}      
        with:
          token: ${{ secrets.PAT }}
          title: 'Merge opshotfix into opsdevelopment'
          body: |
            This is pull request merges changes from the opshotfix branch into the opsdevelopment branch"
          labels: "automerge"
          branch: "opsdevelopment"
          base: "opshotfix/"
