name: Create Pull Request to Development
run-name: Build initiated by ${{ github.actor }}
on:
  push:
    branches:
      - 'opshotfix*'
 
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
     - name: chckout code
       uses: actions/checkout@v2

     - name: Setup github cli
       uses: actions/setup-node@v2
       with:
         node-version: '14'
         
     - name: Raise PR
       env:
         GH_TOKEN: ${{ github.token }}
       run: |
         gh pr create --base main --head ${{ github.ref }} --title "auto pr from opshotfix to main" --body "This is auto pr from opshotfix to main"
