name: "Build Shines Frontend WAR"
run-name: Build initiated by ${{ github.actor }}
on:
  # push:
  #   branches:
  #     - 'opsdevelopment'
  create:
    branches:
      - 'opsrelease/**'
  pull_request:
    types: [opened, closed]
    branches:
      - 'opsrelease/**'
      - 'opsdevelopment'
      - 'main'
      - 'opshotfix/**'

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  codeql_autobuild_check:
    name: CodeQL Analysis and AutoBuild Verification
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Autobuild
      uses: github/codeql-action/autobuild@v3
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"

  build_artifact_for_dev:
    if: >
        github.event.pull_request.merged == true && github.base_ref == 'opsdevelopment'
    runs-on: ubuntu-latest
    needs: [codeql_autobuild_check]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
          ref: ${{ github.ref }}
          fetch-depth: '0'
    - name: Checkout external repository with script
      uses: actions/checkout@v4
      with:
        repository: 'vaingle/mvn-version-bumper'
        ref: 'refs/heads/main'
        #ssh-key: ${{ secrets.DEVOPS_PULL_PRIVATE_KEY }}
        token: ${{ secrets.PAT }}
        #path: 'SHINES-main-rewrite/shines-devops'
        path: mvn-version-bumper
        run: | 
          cd mvn-version-bumper
          ls -lrth
    - name: Setup Java 17 and Maven
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
        #cache-dependency-path: 'SHINES-main-rewrite/pom.xml'
        cache-dependency-path: 'pom.xml'
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Run custom script
      run: |
        echo $TRIGGER_EVENT
        echo $BRANCH_NAME
        #cd SHINES-main-rewrite
        #cd ${{ github.workspace }}/mvn-version-bumper
        chmod +x mvn-version-bumper/versioning.sh
        mvn-version-bumper/versioning.sh $BRANCH_NAME $TRIGGER_EVENT
      env:
        TRIGGER_EVENT: ${{ github.event_name }}
        BRANCH_NAME: ${{ github.ref_name }}
        GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Publish to GitHub Packages
      run: mvn -B deploy
      working-directory: ${{ github.workspace }}
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}

######### hotfix 

  build_artifact_for_hotfix_to_main:
    if: >
      (github.ref_type == 'branch' && startsWith(github.ref, 'refs/heads/opshotfix/')) || 
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && startsWith(github.event.pull_request.base.ref, 'opshotfix/'))
    runs-on: ubuntu-latest
    needs: [codeql_autobuild_check]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
          ref: ${{ github.ref }}
          fetch-depth: '0'
    - name: Checkout external repository with script
      uses: actions/checkout@v4
      with:
        repository: 'vaingle/mvn-version-bumper'
        ref: 'refs/heads/main'
        #ssh-key: ${{ secrets.DEVOPS_PULL_PRIVATE_KEY }}
        token: ${{ secrets.PAT }}
        #path: 'SHINES-main-rewrite/shines-devops'
        path: mvn-version-bumper
    - name: Setup Java 17 and Maven
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
        #cache-dependency-path: 'SHINES-main-rewrite/pom.xml'
        cache-dependency-path: 'pom.xml'
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Run custom script
      run: |
        echo $TRIGGER_EVENT
        echo $BRANCH_NAME
        #cd SHINES-main-rewrite
        #chmod +x shines-devops/mvn_version_bumper.sh
        #shines-devops/mvn_version_bumper.sh $BRANCH_NAME $TRIGGER_EVENT
        chmod +x mvn-version-bumper/versioning.sh
        mvn-version-bumper/versioning.sh $BRANCH_NAME $TRIGGER_EVENT        
      env:
        TRIGGER_EVENT: ${{ github.event_name }}
        BRANCH_NAME: ${{ github.ref_name }}
        GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Publish to GitHub Packages
      run: mvn -B deploy
      working-directory: ${{ github.workspace }}/
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
    #- name: Create Pull request
      #needs: [codeql_autobuild_check, build_artifact_for_hotfix_to_main]
     # uses: octokit/rest.js@v17
     # if: github.event.pull.request.base.ref == 'opsmain' && github.event.pull_request.head.ref == 'opshotfix/'
     # with:
     #   GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
     #   method: post
     #   url: /repos/${{ github.repository }}/pulls
     #   title: 'Automates PR from release into development'
     #   body: |
     #     This is automates pull request created from workflow"
     #   head: opshotfix/
     #   base: opsdevelopment


  ##### hotfix merged to main
  build_artifact_for_main:
    if: >
        github.event.pull_request.merged == true && github.base_ref == 'main'
    runs-on: ubuntu-latest
    needs: [codeql_autobuild_check]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
          ref: ${{ github.ref }}
          fetch-depth: '0'
    - name: Checkout external repository with script
      uses: actions/checkout@v4
      with:
        repository: 'vaingle/mvn-version-bumper'
        ref: 'refs/heads/main'
        #ssh-key: ${{ secrets.DEVOPS_PULL_PRIVATE_KEY }}
        token: ${{ secrets.PAT }}
        #path: 'SHINES-main-rewrite/shines-devops'
        path: mvn-version-bumper
    - name: Setup Java 17 and Maven
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
        #cache-dependency-path: 'SHINES-main-rewrite/pom.xml'
        cache-dependency-path: 'pom.xml'
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Run custom script
      run: |
        echo $TRIGGER_EVENT
        echo $BRANCH_NAME
        #cd SHINES-main-rewrite
        #chmod +x shines-devops/mvn_version_bumper.sh
        #shines-devops/mvn_version_bumper.sh $BRANCH_NAME $TRIGGER_EVENT
        chmod +x mvn-version-bumper/versioning.sh
        mvn-version-bumper/versioning.sh $BRANCH_NAME $TRIGGER_EVENT        
      env:
        TRIGGER_EVENT: ${{ github.event_name }}
        BRANCH_NAME: ${{ github.ref_name }}
        GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Publish to GitHub Packages
      run: mvn -B deploy
      working-directory: ${{ github.workspace }}
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
 
    - name: chckout code from hotfix
      uses: actions/checkout@v2
      with:
        ref: 'refs/heads/hotfix*'
        fetch-depth: '0'

    - name: Setup github cli
      uses: actions/setup-node@v2
      with:
        node-version: '14'
         
    - name: Raise PR
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
         gh pr create --base opsdevelopment --head ${{ github.ref }} --title "auto pr from opshotfix to main" --body "This is auto pr from opshotfix to main"
  
  create_pr_hotfix_dev:
    runs-on: ubuntu-latest
    needs: [codeql_autobuild_check, build_artifact_for_main]
    steps: 
   
    - name: Checkout Repository
      #if: startsWith(github.base_ref, 'opshotfix/')
      uses: actions/checkout@v4
      with:
          ref: "opshotfix/**"
          #fetch-depth: '0'    
    - name: Create Pull request
      uses: peter-evans/create-pull-request@v3
      env:  
        GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}      
      with:
        token: ${{ secrets.PAT }}
        title: 'Merge opshotfix into opsdevelopment'
        body: |
          This is pull request merges changes from the opshotfix branch into the opsdevelopment branch"
        labels: "automerge"
        branch: "opsdevelopment"
        base: "opshotfix/**"
        


  ########## jj
  create_pr:
     runs-on: ubuntu-latest
     needs: [codeql_autobuild_check, build_artifact_for_hotfix_to_main]
     if: github.event.pull.request.base.ref == 'opsdevelopment' && github.event.pull_request.head.ref == 'opsrelease/'
     steps: 
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: '0'
      - name: get commit range
        id: commit_range
        run: echo "::set-output name=range::$(git rev-parse ${{ github.event.before }}..$(git rev-parse ${{ github.sha }})"

      - name: check for new commits
        id: check_commits
        run: |
          commit_range="${{ steps.commit.rage.outputs.range }}"
          if [ -z "$commit_range" ]; then
            echo "No new commits. Exiting"
            exit 0
          fi

      - name: Create Pull request
        if: steps.check_commits.outcome == 'success'
        uses: octokit/rest.js@v17
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          method: post
          url: /repos/${{ github.repository }}/pulls
          title: 'Automates PR from release into development'
          body: |
            This is automates pull request created from workflow"
          head: opsrelease/
          base: opsdevelopment  


  
  build_artifact_for_rel:
    if: >
      (github.ref_type == 'branch' && startsWith(github.ref, 'refs/heads/opsrelease/')) || 
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && startsWith(github.event.pull_request.base.ref, 'opsrelease/'))
    runs-on: ubuntu-latest
    needs: [codeql_autobuild_check]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
          ref: ${{ github.ref }}
          fetch-depth: '0'
    - name: Checkout external repository with script
      uses: actions/checkout@v4
      with:
        repository: 'vaingle/mvn-version-bumper'
        ref: 'refs/heads/main'
        token: ${{ secrets.PAT }}
        #ssh-key: ${{ secrets.DEVOPS_PULL_PRIVATE_KEY }}
        #path: 'SHINES-main-rewrite/shines-devops'
        path: mvn-version-bumper
    - name: Setup Java 17 and Maven
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
        #cache-dependency-path: 'SHINES-main-rewrite/pom.xml'
        cache-dependency-path: 'pom.xml'
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Run custom script
      run: |
        echo $TRIGGER_EVENT
        echo $BRANCH_NAME

        chmod +x mvn-version-bumper/versioning.sh
        mvn-version-bumper/versioning.sh $BRANCH_NAME $TRIGGER_EVENT
      env:
        TRIGGER_EVENT: ${{ github.event_name }}
        BRANCH_NAME: ${{ github.ref_name }}
        GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Publish to GitHub Packages
      run: mvn -B deploy
      working-directory: ${{ github.workspace }}
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
